name: galleria
description: Dart server to listen for Subscriptions from a FHIR server
version: 0.0.10
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  fhir: ^0.11.0
  fhir_at_rest: ^0.11.0
  form_validator: ^2.1.1
  get_it: ^7.2.0
  googleapis: ^10.1.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  mailer: ^6.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.1