name: galleria
description: Dart server to listen for Subscriptions from a FHIR server
version: 0.0.10

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  fhir: ^0.9.3
  fhir_at_rest: ^0.9.3
  form_validator: ^1.0.4
  get_it: ^7.2.0
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  mailer: ^5.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.1