name: server
description: Simple standalone server for serving flutter web apps, utilizing shelf, goal is full stack dart.

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  functions_framework: ^0.4.1
  shelf_static: ^1.1.0