name: galleria
description: Dart server to listen for Subscriptions from a FHIR server
version: 0.0.7

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fhir: ^0.9.0
  fhir_at_rest: ^0.9.0
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  mailer: ^5.2.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3