name: galleria
description: Simple Server to Listen and for FHIR Server Changes for ServiceRequests
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  fhir: ^0.5.0-12
  fhir_at_rest: ^0.5.0-13
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0
  mailer: ^5.1.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2