name: galleria
description: Dart server to listen for Subscriptions from a FHIR server
version: 0.0.9

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  email_validator: ^2.1.17
  fhir: ^0.9.2
  fhir_at_rest: ^0.9.2
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  mailer: ^5.2.0
  phone_numbers_parser: ^7.0.0+1
  shelf: ^1.4.0
  shelf_router: ^1.1.3