name: galleria
description: Simple Server to Listen and for FHIR Server Changes for ServiceRequests
version: 0.0.2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  fhir: ^0.6.0
  fhir_at_rest: ^0.6.1
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.1
  mailer: ^5.1.1
  shelf: ^1.3.0
  shelf_router: ^1.1.2