name: galleria
description: Dart server to listen for Subscriptions from a FHIR server
version: 0.0.6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fhir: ^0.8.0
  fhir_at_rest: ^0.8.0
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.1
  mailer: ^5.1.1
  shelf: ^1.3.0
  shelf_router: ^1.1.2